"""
Generates UCIP-Pitch-Deck-v2.pptx: a 20-slide, 15-minute pitch deck built natively with
python-pptx. Every text element is a real text box, shape or table cell. Only the logo
icon, the product screenshots and the generated world map are images.

v2 differs from build_deck.py (which is left untouched and still builds v1) in five ways:
  - Slides 2 and 3 lead with warming as a global problem, with Mumbai as the first city
    the method was tried on rather than the whole point of it.
  - Slide 3's world panel is generated by make_global_map.py in the ucip repo, from a
    QC-masked MODIS MOD11A2 composite for May 2026. It is the same physical quantity the
    Mumbai pipeline measures, so the two maps are one measurement at two zoom levels.
  - Slide 5 says plainly why Mumbai was the first city, and what porting costs.
  - Slide 8 compares against software that actually ships, led by WRI's Cool Cities Lab
    (March 2026), instead of a table that was mostly policy PDFs.
  - Every string, on-screen and spoken, was rewritten to sound like a person talking.

Structure follows the organizer's 6 mandated sections (TIS x IHFC "Now or Never Hack
2026"), expanded to 20 slides so the talk paces at roughly 45 seconds per slide, leaving
5 of the 20-minute slot for questions. Each slide carries its parent section kicker so
the mandated checklist stays visible.

Speaker notes go in the notes pane and ARE the spoken script. The build asserts the total
spoken time lands between 14:00 and 16:00 at 140 words per minute. The slot is 20 minutes
with 5 reserved for questions, so 16:00 is the hard ceiling and anything at or under 15:00
leaves comfortable slack for a slower delivery.

Every figure in this deck is read from, or verified against, the pipeline's own output:
  data/hvi_pca_log.json      PCA weights, explained variance
  data/sensitivity.json      Kendall tau, top-5 overlap
  data/ward_profiles.json    city means, ward ranks
  data/wards_hvi.geojson     ward HVI values
  data/nbs_recommendations.json  recommendation counts
  frontend/src/lib/citations.ts  citation count

Usage: python build_deck.py   (run from this directory)
"""

import json
import os
import re
import shutil
import sys

# The build log prints slide titles verbatim, some of which contain arrows and degree
# signs. Windows consoles default to cp1252 and would crash on them.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE, MSO_SHAPE_TYPE
from pptx.oxml.ns import qn

# ---------------------------------------------------------------------------
# Brand constants
# ---------------------------------------------------------------------------

BG = "0D1017"
COVER_GLOW = "122024"
PANEL_SOLID = "151A24"
PANEL_NESTED = "1A2029"
BORDER = "2A3040"
INK = "E6EAF2"
MUTED = "9AA3B2"
MUTED_FAINT = "52565D"
LOCKUP_MUTED = "84888F"
SUBTITLE_INK = "BBBEC6"
WHITE = "FFFFFF"
TEAL = "0EA5B3"
EMERALD = "22C55E"
AMBER = "F0A63A"
CRIMSON = "E4572E"

FONT_HEAD = "Inter"
FONT_BODY = "Inter"
FONT_MONO = "JetBrains Mono"

MARGIN_L = 0.55
MARGIN_R = 0.55
SLIDE_W_IN = 13.333
SLIDE_H_IN = 7.5
CONTENT_W = SLIDE_W_IN - MARGIN_L - MARGIN_R  # 12.233
BODY_TOP = 1.30
BODY_BOTTOM = 6.95

TOTAL_SLIDES = 20
WPM = 140.0
MIN_TOTAL_SEC = 14 * 60
MAX_TOTAL_SEC = 16 * 60

REPO = r"C:\Users\lenovo\personal-repos\ucip"
MEDIA_DIR = os.path.join(REPO, "docs", "media")
LOGO_PATH = os.path.join(MEDIA_DIR, "icon-512.png")

OUT_DIR = r"c:\Users\lenovo\EA\projects\ucip"
SHOTS = os.path.join(OUT_DIR, "deck-assets")
OUT_PATH = os.path.join(OUT_DIR, "UCIP-Pitch-Deck-v2.pptx")
BACKUP_PATH = os.path.join(OUT_DIR, "UCIP-Pitch-Deck-v2.bak.pptx")

NO_STYLE_GUID = "{5940675A-B579-460E-94D1-54222C63F5DA}"

SEC = {
    1: "01 \u00b7 PROJECT OVERVIEW & PARTICIPANT DETAILS",
    2: "02 \u00b7 PROBLEM UNDERSTANDING",
    3: "03 \u00b7 RESEARCH & INSIGHTS",
    4: "04 \u00b7 PROPOSED SOLUTION",
    5: "05 \u00b7 PROTOTYPE / SOLUTION DESIGN",
    6: "06 \u00b7 IMPACT & FUTURE SCOPE",
}


# ---------------------------------------------------------------------------
# Live figures, read from the pipeline's own output so the deck cannot drift
# ---------------------------------------------------------------------------

def load_facts():
    def j(*parts):
        with open(os.path.join(REPO, *parts), encoding="utf-8") as fh:
            return json.load(fh)

    pca = j("data", "hvi_pca_log.json")
    sens = j("data", "sensitivity.json")
    prof = j("data", "ward_profiles.json")
    wards = j("data", "wards_hvi.geojson")
    nbs = j("data", "nbs_recommendations.json")

    with open(os.path.join(REPO, "frontend", "src", "lib", "citations.ts"), encoding="utf-8") as fh:
        n_citations = len(re.findall(r'^\s*id:\s*"([^"]+)"', fh.read(), re.M))

    ranked = sorted((f["properties"] for f in wards["features"]), key=lambda p: p["rank"])

    return {
        "pc1": pca["explained_variance_pc1"],
        "weights": pca["weights"],
        "loadings": pca["loadings_pc1"],
        "fallback_used": pca["fallback_used"],
        "tau": sens["mean_kendall_tau"],
        "overlap": sens["mean_top5_overlap"],
        "n_runs": sens["n_runs"],
        "perturb": sens["perturbation_pct"],
        "n_cells": prof["n_cells"],
        "n_wards": prof["n_wards"],
        "city": prof["city"],
        "top5": [(p["ward_id"], p["HVI"]) for p in ranked[:5]],
        "n_nbs": len(nbs),
        "n_citations": n_citations,
        "n_stages": len([f for f in os.listdir(os.path.join(REPO, "pipeline")) if re.match(r"^\d\d_.*\.py$", f)]),
    }


F = load_facts()

# ---------------------------------------------------------------------------
# Presentation setup
# ---------------------------------------------------------------------------

prs = Presentation()
prs.slide_width = Inches(SLIDE_W_IN)
prs.slide_height = Inches(SLIDE_H_IN)
BLANK_LAYOUT = prs.slide_layouts[6]


def rgb(hexstr):
    return RGBColor.from_string(hexstr)


def new_slide():
    return prs.slides.add_slide(BLANK_LAYOUT)


def set_background(slide):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = rgb(BG)


def set_notes(slide, text):
    slide.notes_slide.notes_text_frame.text = " ".join(text.split())


# ---------------------------------------------------------------------------
# Low-level text/shape helpers
# ---------------------------------------------------------------------------

def _set_run(run, text, font=FONT_BODY, size=11, color=INK, bold=False, italic=False):
    run.text = text
    run.font.name = font
    run.font.size = Pt(size)
    run.font.color.rgb = rgb(color)
    run.font.bold = bold
    run.font.italic = italic


def add_textbox(slide, x, y, w, h, word_wrap=True, anchor=MSO_ANCHOR.TOP):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = word_wrap
    tf.vertical_anchor = anchor
    tf.margin_left = 0
    tf.margin_right = 0
    tf.margin_top = 0
    tf.margin_bottom = 0
    return tb, tf


def add_kicker(slide, text, x=MARGIN_L, y=0.35, w=9.6, h=0.24):
    tb, tf = add_textbox(slide, x, y, w, h)
    r = tf.paragraphs[0].add_run()
    _set_run(r, text.upper(), font=FONT_MONO, size=11, color=TEAL, bold=True)
    return tb


def add_heading(slide, text, x, y, w, h, size=26, color=WHITE):
    tb, tf = add_textbox(slide, x, y, w, h)
    r = tf.paragraphs[0].add_run()
    _set_run(r, text, font=FONT_HEAD, size=size, color=color, bold=True)
    return tb


def add_gradient_bar(slide, x=MARGIN_L, y=1.15, w=0.9, h=0.055, angle=0.0):
    shp = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    shp.adjustments[0] = 0.5
    shp.line.fill.background()
    shp.shadow.inherit = False
    shp.fill.gradient()
    stops = shp.fill.gradient_stops
    stops[0].color.rgb = rgb(TEAL)
    stops[0].position = 0.0
    stops[-1].color.rgb = rgb(EMERALD)
    stops[-1].position = 1.0
    shp.fill.gradient_angle = angle
    return shp


def add_dot_heading(slide, text, x, y, w, h, size=13, dot=EMERALD):
    tb, tf = add_textbox(slide, x, y, w, h)
    p = tf.paragraphs[0]
    r1 = p.add_run()
    _set_run(r1, "\u25CF ", font=FONT_BODY, size=size, color=dot, bold=True)
    r2 = p.add_run()
    _set_run(r2, text, font=FONT_HEAD, size=size, color=WHITE, bold=True)
    return tb


def add_body_text(slide, text, x, y, w, h, size=11, color=MUTED, bold=False,
                  align=PP_ALIGN.LEFT, line_spacing=1.18, font=FONT_BODY,
                  anchor=MSO_ANCHOR.TOP, space_before=4):
    tb, tf = add_textbox(slide, x, y, w, h, anchor=anchor)
    lines = text.split("\n") if isinstance(text, str) else list(text)
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = line_spacing
        if i > 0:
            p.space_before = Pt(space_before)
        r = p.add_run()
        _set_run(r, line, font=font, size=size, color=color, bold=bold)
    return tb


def add_lead_body(slide, x, y, w, h, lead, rest, lead_size=11, rest_size=10.5,
                  lead_color=WHITE, rest_color=MUTED, anchor=MSO_ANCHOR.TOP, line_spacing=1.15):
    tb, tf = add_textbox(slide, x, y, w, h, anchor=anchor)
    p = tf.paragraphs[0]
    p.line_spacing = line_spacing
    r1 = p.add_run()
    _set_run(r1, lead + " ", font=FONT_HEAD, size=lead_size, color=lead_color, bold=True)
    r2 = p.add_run()
    _set_run(r2, rest, font=FONT_BODY, size=rest_size, color=rest_color, bold=False)
    return tb


def add_card_bg(slide, x, y, w, h, fill=PANEL_SOLID, border=BORDER, radius=0.06):
    shp = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    shp.adjustments[0] = radius
    shp.fill.solid()
    shp.fill.fore_color.rgb = rgb(fill)
    shp.line.color.rgb = rgb(border)
    shp.line.width = Pt(0.75)
    shp.shadow.inherit = False
    return shp


def add_card(slide, x, y, w, h, heading, body, pad=0.20, heading_size=12.5,
             body_size=10, body_color=MUTED, dot=EMERALD):
    add_card_bg(slide, x, y, w, h)
    add_dot_heading(slide, heading, x + pad, y + pad * 0.7, w - 2 * pad, 0.30,
                    size=heading_size, dot=dot)
    body_y = y + pad * 0.7 + 0.38
    add_body_text(slide, body, x + pad, body_y, w - 2 * pad, h - (body_y - y) - pad,
                  size=body_size, color=body_color)


def add_stat_box(slide, x, y, w, h, number, label, number_size=18, layout="stacked",
                 number_color=EMERALD):
    add_card_bg(slide, x, y, w, h, fill=PANEL_NESTED)
    pad = 0.14
    if layout == "stacked":
        add_body_text(slide, number, x + pad, y, w - 2 * pad, h * 0.58, size=number_size,
                      color=number_color, bold=True, font=FONT_MONO, anchor=MSO_ANCHOR.BOTTOM)
        add_body_text(slide, label, x + pad, y + h * 0.58, w - 2 * pad, h * 0.40, size=8.5,
                      color=MUTED, anchor=MSO_ANCHOR.TOP, line_spacing=1.1)
    else:
        num_w = w * 0.34
        add_body_text(slide, number, x + pad, y, num_w - pad, h, size=number_size,
                      color=number_color, bold=True, font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE)
        add_body_text(slide, label, x + num_w, y, w - num_w - pad, h, size=9.5, color=MUTED,
                      anchor=MSO_ANCHOR.MIDDLE, line_spacing=1.1)


def add_pill_list(slide, x, y, w, h, items, gap=0.12, lead_size=11, rest_size=10):
    n = len(items)
    item_h = (h - gap * (n - 1)) / n
    cy = y
    for lead, rest in items:
        add_card_bg(slide, x, cy, w, item_h, fill=PANEL_NESTED)
        pad = 0.16
        add_lead_body(slide, x + pad, cy, w - 2 * pad, item_h, lead, rest,
                      lead_size=lead_size, rest_size=rest_size, anchor=MSO_ANCHOR.MIDDLE)
        cy += item_h + gap


def add_callout(slide, x, y, w, h, number, text, number_size=20, accent=AMBER):
    add_card_bg(slide, x, y, w, h, fill=PANEL_NESTED, border=accent)
    pad = 0.16
    num_w = 1.45
    add_body_text(slide, number, x + pad, y, num_w, h, size=number_size, color=accent,
                  bold=True, font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE)
    add_body_text(slide, text, x + pad + num_w, y + 0.06, w - num_w - 2 * pad, h - 0.12,
                  size=9.5, color=MUTED, anchor=MSO_ANCHOR.MIDDLE, line_spacing=1.15)


def strip_table_style(table):
    table.first_row = False
    table.horz_banding = False
    tbl = table._tbl
    tblPr = tbl.find(qn("a:tblPr"))
    if tblPr is None:
        return
    style_el = tblPr.find(qn("a:tableStyleId"))
    if style_el is None:
        style_el = tblPr.makeelement(qn("a:tableStyleId"), {})
        tblPr.append(style_el)
    style_el.text = NO_STYLE_GUID


def add_table(slide, x, y, w, h, headers, rows, col_widths, header_fill=TEAL,
              body_size=8.8, header_size=9.5, highlight_last=False):
    n_rows = len(rows) + 1
    n_cols = len(headers)
    gframe = slide.shapes.add_table(n_rows, n_cols, Inches(x), Inches(y), Inches(w), Inches(h))
    table = gframe.table
    strip_table_style(table)

    for i, cw in enumerate(col_widths):
        table.columns[i].width = Inches(cw)
    header_h = 0.32
    data_h = (h - header_h) / len(rows) if rows else 0.4
    table.rows[0].height = Inches(header_h)
    for r in range(1, n_rows):
        table.rows[r].height = Inches(data_h)

    def style_cell(cell, text, size, color, bold=False, fill=PANEL_SOLID, align=PP_ALIGN.LEFT,
                   font=FONT_BODY):
        cell.margin_left = Inches(0.08)
        cell.margin_right = Inches(0.08)
        cell.margin_top = Inches(0.03)
        cell.margin_bottom = Inches(0.03)
        cell.vertical_anchor = MSO_ANCHOR.MIDDLE
        cell.fill.solid()
        cell.fill.fore_color.rgb = rgb(fill)
        cell.text = text
        # A newline in `text` creates extra paragraphs. Style every one of them, otherwise
        # continuation lines silently fall back to the 18 pt theme default.
        for p in cell.text_frame.paragraphs:
            p.alignment = align
            p.line_spacing = 1.05
            for run in p.runs:
                run.font.name = font
                run.font.size = Pt(size)
                run.font.bold = bold
                run.font.color.rgb = rgb(color)

    for c, htext in enumerate(headers):
        style_cell(table.cell(0, c), htext, header_size, WHITE, bold=True, fill=header_fill)
    for ridx, row in enumerate(rows, start=1):
        is_last = highlight_last and ridx == len(rows)
        for c, val in enumerate(row):
            if is_last:
                color = EMERALD if c == 0 else INK
                fill = PANEL_NESTED
            else:
                color = INK if c == 0 else MUTED
                fill = PANEL_SOLID
            style_cell(table.cell(ridx, c), val, body_size, color,
                       bold=(c == 0 or is_last), fill=fill)
    return table


def add_bar_row(slide, x, y, w, h, label, frac, value_text, label_w=2.05, value_w=0.75,
                bar_color=TEAL, label_size=9.5):
    add_body_text(slide, label, x, y, label_w, h, size=label_size, color=INK,
                  anchor=MSO_ANCHOR.MIDDLE)
    track_x = x + label_w
    track_w = w - label_w - value_w - 0.12
    track = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(track_x),
                                   Inches(y + h * 0.30), Inches(track_w), Inches(h * 0.40))
    track.adjustments[0] = 0.5
    track.fill.solid()
    track.fill.fore_color.rgb = rgb(PANEL_NESTED)
    track.line.color.rgb = rgb(BORDER)
    track.line.width = Pt(0.5)
    track.shadow.inherit = False
    fill_w = max(0.06, track_w * frac)
    bar = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(track_x),
                                 Inches(y + h * 0.30), Inches(fill_w), Inches(h * 0.40))
    bar.adjustments[0] = 0.5
    bar.fill.solid()
    bar.fill.fore_color.rgb = rgb(bar_color)
    bar.line.fill.background()
    bar.shadow.inherit = False
    add_body_text(slide, value_text, x + w - value_w, y, value_w, h, size=9.5, color=INK,
                  bold=True, font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE, align=PP_ALIGN.RIGHT)


def add_flow_box(slide, x, y, w, h, num, name, detail, accent=TEAL):
    add_card_bg(slide, x, y, w, h)
    tb, tf = add_textbox(slide, x + 0.08, y + 0.08, w - 0.16, h - 0.16, anchor=MSO_ANCHOR.MIDDLE)
    p0 = tf.paragraphs[0]
    p0.alignment = PP_ALIGN.CENTER
    _set_run(p0.add_run(), num, font=FONT_MONO, size=8, color=accent, bold=True)
    p1 = tf.add_paragraph()
    p1.alignment = PP_ALIGN.CENTER
    p1.space_before = Pt(2)
    _set_run(p1.add_run(), name, font=FONT_HEAD, size=10, color=WHITE, bold=True)
    p2 = tf.add_paragraph()
    p2.alignment = PP_ALIGN.CENTER
    p2.space_before = Pt(1)
    _set_run(p2.add_run(), detail, font=FONT_BODY, size=7.8, color=MUTED)


def add_arrow(slide, x, y, w, h, color=BORDER):
    shp = slide.shapes.add_shape(MSO_SHAPE.RIGHT_ARROW, Inches(x), Inches(y), Inches(w), Inches(h))
    shp.fill.solid()
    shp.fill.fore_color.rgb = rgb(color)
    shp.line.fill.background()
    shp.shadow.inherit = False
    return shp


def add_brand_lockup(slide):
    x_icon, y_icon = 11.85, 0.30
    slide.shapes.add_picture(LOGO_PATH, Inches(x_icon), Inches(y_icon),
                             width=Inches(0.20), height=Inches(0.20))
    tb, tf = add_textbox(slide, x_icon + 0.28, y_icon - 0.01, 0.70, 0.24, anchor=MSO_ANCHOR.MIDDLE)
    _set_run(tf.paragraphs[0].add_run(), "UCIP", font=FONT_MONO, size=10.5,
             color=LOCKUP_MUTED, bold=True)


def add_slide_number(slide, n, total=TOTAL_SLIDES):
    tb, tf = add_textbox(slide, 11.9, 7.14, 0.88, 0.28, anchor=MSO_ANCHOR.MIDDLE)
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.RIGHT
    _set_run(p.add_run(), f"{n} / {total}", font=FONT_MONO, size=9, color=MUTED_FAINT)


def add_screenshot(slide, filename, x, y, w, caption=None, caption_size=8.2):
    path = os.path.join(SHOTS, filename)
    pic = slide.shapes.add_picture(path, Inches(x), Inches(y), width=Inches(w))
    pic.line.color.rgb = rgb(BORDER)
    pic.line.width = Pt(0.75)
    bottom = y + (pic.height / 914400.0)
    if caption:
        add_body_text(slide, caption, x, bottom + 0.07, w, 0.40, size=caption_size, color=MUTED,
                      align=PP_ALIGN.CENTER, line_spacing=1.12)
    return pic, bottom


def add_crop_screenshot(slide, filename, x, y, w, crop_l=0.0, crop_r=0.0,
                        crop_t=0.0, crop_b=0.0, caption=None, caption_size=8.2,
                        max_h=None, center_in=None):
    """Place a cropped screenshot at width `w`, computing height from the visible crop.

    Height is derived, never passed in. Hardcoding both dimensions silently stretches the
    image whenever a crop is retuned, which is exactly the bug this replaced.
    If `max_h` is given and the derived height exceeds it, the whole image scales down and
    is optionally re-centred inside a `center_in` width.
    """
    path = os.path.join(SHOTS, filename)
    probe = slide.shapes.add_picture(path, Inches(x), Inches(y), width=Inches(w))
    native_aspect = probe.width / probe.height
    probe._element.getparent().remove(probe._element)

    w_frac = 1.0 - crop_l - crop_r
    h_frac = 1.0 - crop_t - crop_b
    if w_frac <= 0 or h_frac <= 0:
        raise ValueError(f"{filename}: crop removes the entire image")
    visible_aspect = native_aspect * w_frac / h_frac

    h = w / visible_aspect
    if max_h is not None and h > max_h:
        w = max_h * visible_aspect
        h = max_h
        if center_in:
            x = x + (center_in - w) / 2.0

    pic = slide.shapes.add_picture(path, Inches(x), Inches(y), width=Inches(w), height=Inches(h))
    pic.crop_left = crop_l
    pic.crop_right = crop_r
    pic.crop_top = crop_t
    pic.crop_bottom = crop_b
    pic.line.color.rgb = rgb(BORDER)
    pic.line.width = Pt(0.75)
    if caption:
        add_body_text(slide, caption, x, y + h + 0.07, w, 0.40, size=caption_size, color=MUTED,
                      align=PP_ALIGN.CENTER, line_spacing=1.12)
    return x, y, w, h


def base_slide(n, section, heading_text, heading_size=25, sub=None):
    slide = new_slide()
    set_background(slide)
    add_kicker(slide, SEC[section])
    add_heading(slide, heading_text, MARGIN_L, 0.60, 10.8, 0.50, size=heading_size)
    add_gradient_bar(slide)
    if sub:
        add_body_text(slide, sub, MARGIN_L, 1.32, 11.0, 0.30, size=10.5, color=SUBTITLE_INK)
    add_brand_lockup(slide)
    add_slide_number(slide, n)
    return slide


def pct(x):
    return f"{x * 100:.1f}%"


# ---------------------------------------------------------------------------
# 01 - PROJECT OVERVIEW & PARTICIPANT DETAILS
# ---------------------------------------------------------------------------

def slide_01_title():
    slide = new_slide()
    set_background(slide)

    glow = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(-2.0), Inches(-1.5), Inches(9.0), Inches(6.5))
    glow.line.fill.background()
    glow.shadow.inherit = False
    glow.fill.gradient()
    stops = glow.fill.gradient_stops
    stops[0].color.rgb = rgb(COVER_GLOW)
    stops[0].position = 0.0
    stops[-1].color.rgb = rgb(BG)
    stops[-1].position = 1.0
    glow.fill.gradient_angle = 45.0

    add_kicker(slide, SEC[1])
    # Text column is capped at 6.85 in so it clears the hero image parked at x = 7.55.
    add_heading(slide, "UCIP: Urban Climate Intelligence Platform", MARGIN_L, 1.72, 6.85, 1.6, size=34)
    add_gradient_bar(slide, x=MARGIN_L, y=3.40, w=1.3, h=0.06)
    add_body_text(
        slide,
        "Cities are getting hotter and every one of them has to pick somewhere to start. "
        "This works out which of Mumbai's 24 wards to cool first, and what to build there.",
        MARGIN_L, 3.62, 6.60, 0.9, size=14, color=SUBTITLE_INK, line_spacing=1.3,
    )

    add_card_bg(slide, MARGIN_L, 4.65, 6.5, 2.30)
    meta_rows = [
        ("STUDENT NAME", "Anay Dhawan"),
        ("SCHOOL", "NES International School Mumbai"),
        ("GRADE", "11 (IBDP Year 1)"),
        ("DOMAIN", "PLANET"),
        ("FOCUS AREA", "Urban heat resilience, climate adaptation"),
    ]
    ty = 4.80
    row_h = 2.00 / 5
    for label, value in meta_rows:
        add_body_text(slide, label, MARGIN_L + 0.20, ty, 2.0, row_h, size=9, color=MUTED,
                      font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE)
        add_body_text(slide, value, MARGIN_L + 2.30, ty, 3.90, row_h, size=11.5, color=INK,
                      bold=True, anchor=MSO_ANCHOR.MIDDLE)
        ty += row_h

    # crop_l clears the hero headline entirely; anything under 0.44 leaves "el" of "ward-level".
    add_crop_screenshot(slide, "deck-hero-dark.png", 7.55, 1.72, 5.25,
                        crop_l=0.46, crop_r=0.0, crop_t=0.10, crop_b=0.02,
                        max_h=4.42, center_in=5.25,
                        caption="All 24 wards, extruded and coloured by their real vulnerability score.",
                        caption_size=8.5)

    add_brand_lockup(slide)
    add_slide_number(slide, 1)

    set_notes(slide, """
        Good morning. I am Anay Dhawan, Grade 11 at NES International School Mumbai, and this
        is UCIP, built for the PLANET domain. Cities everywhere are getting hotter, and every
        one of them eventually has to pick somewhere to start spending. UCIP works out which of
        Mumbai's twenty four wards to cool first, and what to build there. Over the next fifteen
        minutes I will show you the problem, the method behind it, and the working site.
    """)


def slide_02_claim():
    slide = new_slide()
    set_background(slide)
    add_kicker(slide, SEC[1])
    add_gradient_bar(slide, x=MARGIN_L, y=1.05, w=1.3, h=0.06)

    add_body_text(
        slide,
        "Cities everywhere are heating up.\nVery few of them can say which neighbourhood\n"
        "to cool first, or what to put there.",
        MARGIN_L, 1.55, 11.8, 2.0, size=29, color=WHITE, bold=True, line_spacing=1.22,
        font=FONT_HEAD,
    )
    add_body_text(slide, "UCIP is a way of making that call. Mumbai is where I tried it first.",
                  MARGIN_L, 3.62, 11.8, 0.5, size=24,
                  color=TEAL, bold=True, font=FONT_HEAD)

    add_body_text(slide, "THE NEXT FIFTEEN MINUTES", MARGIN_L, 4.75, 6.0, 0.26, size=9.5,
                  color=MUTED, font=FONT_MONO, bold=True)

    steps = [
        ("01", "The problem", "why a city-wide plan\nis not enough"),
        ("02", "The research", "what already ships,\nand what it misses"),
        ("03", "The method", "seven indicators, PCA weights,\nsensitivity-tested"),
        ("04", "The product", "a live dashboard you\ncan click through"),
        ("05", "The limits", "what this tool\ndoes not know"),
        ("06", "What's next", "finer grid, more cities,\nbudget layer"),
    ]
    bw, gap = 1.86, 0.18
    bx = MARGIN_L
    for num, name, detail in steps:
        add_flow_box(slide, bx, 5.12, bw, 1.28, num, name, detail)
        bx += bw + gap

    add_brand_lockup(slide)
    add_slide_number(slide, 2)

    set_notes(slide, """
        Warming is global, but nobody cools a planet. You cool a neighbourhood, with a budget
        that runs out. So every city eventually hits the same question: which one goes first.
        Mumbai is not short of heat data, there are strong studies from IIT Bombay and the city
        has its own climate plan. What is missing comes one step later. Twenty four wards, one
        budget, and no defensible way to say this one before that one. Right now that call is
        intuition. UCIP turns it into something anyone can re-run and check.
    """)


# ---------------------------------------------------------------------------
# 02 - PROBLEM UNDERSTANDING
# ---------------------------------------------------------------------------

def slide_03_uneven():
    slide = base_slide(3, 2, "Warming is global. The heat that hurts people is local.")
    city = F["city"]

    add_body_text(
        slide,
        "Both maps here are my own Earth Engine runs, measuring the same thing at two zoom "
        "levels. Nothing on this slide is quoted from a report.",
        MARGIN_L, 1.34, 7.4, 0.32, size=10.5, color=SUBTITLE_INK,
    )

    add_callout(slide, MARGIN_L, 1.86, 7.4, 1.05, "13.7 \u00b0C",
                "spread in land-surface temperature between the coolest and hottest "
                "square kilometre inside a single city, from 26.2 \u00b0C to 40.0 \u00b0C.",
                number_size=26, accent=CRIMSON)

    rows = [
        ("Land-surface temperature", "26.2 to 40.0 \u00b0C", f"{city['LST_C']:.1f} \u00b0C"),
        ("Green cover (NDVI index)", "-0.07 to 0.71", f"{city['NDVI']:.2f}"),
        ("Impervious / built-up", "0 to 96.8 %", f"{city['impervious_pct']:.0f} %"),
        ("Population density", "16 to 115,272 /km\u00b2", f"{city['pop_density_km2']:,.0f} /km\u00b2"),
        ("Distance to nearest hospital", "4 m to 6.2 km", f"{city['hospital_dist_m']:,.0f} m"),
    ]
    add_table(slide, MARGIN_L, 3.16, 7.4, 2.94,
              ["INDICATOR", "RANGE ACROSS THE CITY", "CITY MEAN"],
              rows, [3.0, 2.55, 1.85], body_size=9.4)

    add_body_text(
        slide,
        "A city-wide average hides all of this. Every one of these gaps is somewhere you could "
        "aim a budget.",
        MARGIN_L, 6.30, 7.4, 0.4, size=10.5, color=INK, bold=True,
    )

    # The generated world map is wide and short (about 2.2:1), so it sits at the top of the
    # right column and a card fills the space underneath rather than leaving a gap.
    _, _, _, mh = add_crop_screenshot(
        slide, "deck-global-lst-may2026.png", 8.30, 1.90, 4.48,
        crop_l=0.0, crop_r=0.0, crop_t=0.0, crop_b=0.0,
        max_h=2.60, center_in=4.48)
    add_body_text(
        slide,
        "My own Earth Engine run. MODIS land surface temperature, May 2026, "
        "quality-masked. Grey is ocean or cloud gap, not cold.",
        8.30, 1.90 + mh + 0.09, 4.48, 0.50, size=8.2, color=MUTED,
        align=PP_ALIGN.CENTER, line_spacing=1.15,
    )

    add_card_bg(slide, 8.30, 4.62, 4.48, 1.68, fill=PANEL_NESTED, border=TEAL)
    add_dot_heading(slide, "Same instrument, two scales", 8.56, 4.80, 4.0, 0.28,
                    size=12, dot=TEAL)
    add_body_text(
        slide,
        "The world map above is MODIS at 1 km. Every Mumbai map later in this deck is Landsat "
        "at 30 m, measuring the same thing. Warming shows up as a planetary trend and lands as "
        "a street-level problem, and only the street-level version tells you where to spend.",
        8.56, 5.18, 4.0, 1.02, size=9.4, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        On the right is a world land surface temperature map for May twenty twenty six. I made
        it this week off MODIS, quality masked, through the same Earth Engine account that runs
        everything else here. One month, so the north reads warm, and grey is ocean or cloud
        gap, not cold. On the left is Mumbai, measured the same way, running from twenty six to
        forty degrees. That is a thirteen point seven degree spread inside one city from a
        single satellite pass. Warming is planetary, the damage is street level, and a city-wide
        average hides every gap you could aim a budget at.
    """)


def slide_04_who():
    slide = base_slide(4, 2, "The burden is not shared evenly either")

    # 4 equal cards, gap=0.18, card_w=(CONTENT_W - 3*0.18)/4 = 2.923
    cw = 2.923
    cx1 = MARGIN_L
    cx2 = MARGIN_L + 3.103
    cx3 = MARGIN_L + 6.206
    cx4 = MARGIN_L + 9.309

    add_card(slide, cx1, 1.75, cw, 2.35, "Slum households",
             "Metal and asbestos roofs trap heat by day, release it at night. Cooling access is "
             "lowest where indoor heat is highest.", dot=CRIMSON)
    add_card(slide, cx2, 1.75, cw, 2.35, "Elderly residents",
             "Heat mortality concentrates sharply with age. Elderly residents are also least able "
             "to relocate during a heat event.", dot=AMBER)
    add_card(slide, cx3, 1.75, cw, 2.35, "Wards far from care",
             "Heat illness is time-critical. Hospital distance ranges from four metres to over "
             "six kilometres across the city.", dot=TEAL)
    add_card(slide, cx4, 1.75, cw, 2.35, "Everyday commuters",
             "Bus stops and rail platforms offer little shade. Anyone waiting for transit absorbs "
             "the same heat exposure, with no home to retreat to.", dot=EMERALD)

    add_card_bg(slide, MARGIN_L, 4.35, 11.94, 1.95, fill=PANEL_NESTED, border=TEAL)
    add_body_text(slide, "THE PART THAT MAKES THIS HARD", MARGIN_L + 0.30, 4.55, 6.0, 0.26,
                  size=9.5, color=TEAL, font=FONT_MONO, bold=True)
    add_body_text(
        slide,
        "Vulnerability is highest exactly where the data is scarcest.",
        MARGIN_L + 0.30, 4.88, 11.3, 0.42, size=19, color=WHITE, bold=True, font=FONT_HEAD,
    )
    add_body_text(
        slide,
        "Informal settlements are, almost by definition, under-surveyed. That is precisely why "
        "UCIP is built on open satellite and modelled-population data rather than waiting on a "
        "ward-level census that does not exist. It is also why I state plainly, later in this "
        "deck, which of my own layers are proxies.",
        MARGIN_L + 0.30, 5.42, 11.3, 0.75, size=10.5, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        Who actually carries this. Four groups. Slum households, where metal and asbestos roofs
        trap heat by day, release it at night. Elderly residents, where heat mortality
        concentrates sharply with age. Anyone far from care, since hospital distance ranges from
        four metres to over six kilometres. And everyday commuters, since bus stops and rail
        platforms offer no shade. Vulnerability is highest exactly where the data is scarcest:
        informal settlements are under-surveyed almost by definition, which is why UCIP is built
        on open satellite and modelled population data instead of a census that does not exist.
    """)


def slide_05_matters():
    slide = base_slide(5, 2, "Why this matters, and what is actually missing")

    add_card(slide, MARGIN_L, 1.75, 5.85, 2.05, "Heat is India's deadliest weather hazard",
             "It kills more people than floods or cyclones, and it does so quietly, spread across "
             "a season rather than concentrated in one visible disaster. That makes it easy to "
             "under-invest in.")

    add_callout(slide, MARGIN_L, 4.00, 5.85, 1.30, "~1,190",
                "lives saved per year in Ahmedabad once heat action was targeted locally rather "
                "than declared city-wide (Knowlton et al. 2014, IJERPH). Targeting is the "
                "variable that moved the number.",
                number_size=25, accent=EMERALD)

    add_card_bg(slide, MARGIN_L + 6.09, 1.75, 5.85, 3.55, border=CRIMSON)
    add_dot_heading(slide, "The gap Mumbai actually has", MARGIN_L + 6.34, 1.95, 5.35, 0.30,
                    size=13, dot=CRIMSON)
    add_body_text(
        slide,
        "The Mumbai Climate Action Plan 2022 names heat as a priority pillar. It sets city-wide "
        "goals, and it is a serious document.\n"
        "But it stops at strategy. It does not contain a reproducible method for answering the "
        "one question a planner with a finite budget has to answer first:\n"
        "which ward gets cooled before the others, and on what evidence?\n"
        "That is a targeting gap, not a data gap. Mumbai has the data. It does not have the "
        "decision layer that sits on top of it.",
        MARGIN_L + 6.34, 2.40, 5.35, 2.75, size=10.5, color=MUTED, line_spacing=1.22,
        space_before=7,
    )

    add_card_bg(slide, MARGIN_L, 5.50, 5.85, 1.32, fill=PANEL_NESTED, border=TEAL)
    add_dot_heading(slide, "Why Mumbai first", MARGIN_L + 0.26, 5.68, 5.3, 0.28,
                    size=12, dot=TEAL)
    add_body_text(
        slide,
        "Because I live here. I can hold the output against streets I actually walk, and if the "
        "index calls a ward brutal I usually already know whether it is. No other city gives me "
        "that check.",
        MARGIN_L + 0.26, 6.04, 5.3, 0.70, size=9.4, color=MUTED, line_spacing=1.2,
    )

    add_card_bg(slide, MARGIN_L + 6.09, 5.50, 5.85, 1.32, fill=PANEL_NESTED)
    add_dot_heading(slide, "What it costs to move it", MARGIN_L + 6.35, 5.68, 5.3, 0.28,
                    size=12, dot=EMERALD)
    add_body_text(
        slide,
        "Every input is free and public, so the next city needs a different boundary file rather "
        "than a different method or a data budget. The build is Mumbai-shaped today. The method "
        "is not.",
        MARGIN_L + 6.35, 6.04, 5.3, 0.70, size=9.4, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        Heat is India's deadliest weather hazard. It kills more people than floods or cyclones,
        but quietly, across a whole season, which makes it easy to under-invest in. The best
        evidence that targeting works is Ahmedabad: Knowlton and colleagues, twenty fourteen,
        estimate around eleven hundred and ninety lives saved a year once heat action was aimed
        locally instead of declared city-wide. Mumbai's climate plan names heat as a priority
        but stops at strategy. That is a targeting gap, not a data gap. And why Mumbai,
        honestly: I live here. I can hold the output against streets I actually walk, which is a
        check I would not get anywhere else.
    """)


# ---------------------------------------------------------------------------
# 03 - RESEARCH & INSIGHTS
# ---------------------------------------------------------------------------

def slide_06_measured():
    slide = base_slide(6, 3, "What I measured, not what I looked up",
                       sub="Every figure in this deck comes out of a pipeline I ran, on free and public data.")

    city = F["city"]
    stats = [
        ("12", "Landsat 8/9 scenes\ncomposited"),
        (f"{city['LST_C']:.1f} \u00b0C", "mean land-surface\ntemperature, city-wide"),
        (f"{city['NDVI']:.2f}", "mean NDVI\ngreen-cover index"),
        (f"{F['n_cells']}", "1 km cells scored\nacross 24 wards"),
    ]
    bw, gap = 2.88, 0.20
    bx = MARGIN_L
    for num, label in stats:
        add_stat_box(slide, bx, 1.86, bw, 1.05, num, label, number_size=19)
        bx += bw + gap

    rows = [
        ("Landsat 8 & 9 Collection 2 L2", "USGS via Google Earth Engine",
         "Surface temperature, NDVI", "30 m"),
        ("ESA WorldCover v200", "ESA via Google Earth Engine",
         "Impervious cover, land class", "10 m"),
        ("WorldPop pop_age_sex (IND_2020)", "WorldPop via Google Earth Engine",
         "Population, elderly share", "100 m"),
        ("OpenStreetMap (osmnx)", "OSM contributors, ODbL",
         "Hospital locations", "vector"),
        ("Datameet Municipal Spatial Data", "Datameet, open",
         "BMC ward boundaries, slum clusters", "vector"),
    ]
    add_table(slide, MARGIN_L, 3.20, 11.94, 2.45,
              ["DATASET", "PROVENANCE", "WHAT IT CONTRIBUTES", "RES."],
              rows, [3.85, 3.25, 3.64, 1.20])

    add_body_text(
        slide,
        "Dry-season window, November 2025 to February 2026. Cloud cover under 20 percent, "
        "cloud and shadow masked per pixel, median composite.",
        MARGIN_L, 5.80, 7.6, 0.4, size=10, color=MUTED,
    )
    add_body_text(
        slide,
        f"{F['n_citations']} papers cited. Every DOI verified.",
        8.55, 5.80, 4.0, 0.4, size=10.5, color=EMERALD, bold=True, align=PP_ALIGN.RIGHT,
    )

    set_notes(slide, """
        This section is research: what I measured, versus what I read. I built a live pipeline on
        Google Earth Engine, compositing twelve Landsat scenes over the dry season, masked for
        cloud and shadow at pixel level, giving a mean land surface temperature of thirty two
        point four degrees over five hundred and forty one cells, all from my own run. The
        datasets underneath are free and public: Landsat, ESA land cover, WorldPop, OpenStreetMap,
        Datameet. Anyone can reproduce this, and any other city can run it.
    """)


def slide_07_literature():
    slide = base_slide(7, 3, "What the literature says, including the inconvenient part")

    add_card(slide, MARGIN_L, 1.75, 3.86, 2.45, "Canopy cooling is nonlinear",
             "Below roughly 40 % canopy cover, daytime cooling is negligible. Between 40 and 80 % "
             "you get about 1 \u00b0C. Planting a few trees in a bare ward buys almost nothing.\n\n"
             "Ziter et al. 2019, PNAS", dot=EMERALD)

    add_card(slide, MARGIN_L + 4.04, 1.75, 3.86, 2.45, "Cool roofs are the reliable lever",
             "Roughly 0.6 K of peak cooling per +0.1 albedo, quoted at the conservative end of the "
             "published range. Cheap, fast, and it works on exactly the roofs that trap the most "
             "heat.\n\nSantamouris 2014, Solar Energy", dot=TEAL)

    add_card(slide, MARGIN_L + 8.08, 1.75, 3.86, 2.45, "The inconvenient finding",
             "Planting trees on native grassland is ecologically harmful. Restoration potential is "
             "real, but it is not everywhere, and treating it as everywhere causes damage.\n\n"
             "Bastin et al. 2019 vs Veldman et al. 2019, Science", dot=CRIMSON)

    add_card_bg(slide, MARGIN_L, 4.45, 11.94, 1.85, fill=PANEL_NESTED, border=CRIMSON)
    add_body_text(slide, "WHY THIS ONE CHANGED THE DESIGN", MARGIN_L + 0.30, 4.65, 7.0, 0.26,
                  size=9.5, color=CRIMSON, font=FONT_MONO, bold=True)
    add_body_text(
        slide,
        "Almost every urban-greening tool answers heat with \"plant more trees\". The Bastin and "
        "Veldman exchange in Science says that is wrong often enough to matter. So UCIP does not "
        "recommend planting until it has checked whether planting belongs there, and when the "
        "answer is no, it says no and routes to cool roofs instead. That guardrail is the single "
        "biggest design consequence of the reading, and I will show it running on slide sixteen.",
        MARGIN_L + 0.30, 4.98, 11.3, 1.15, size=10.5, color=MUTED, line_spacing=1.22,
    )

    set_notes(slide, """
        Three findings shaped the build. First, canopy cooling is nonlinear: Ziter and colleagues
        in PNAS found that below roughly forty percent canopy cover, daytime cooling is basically
        negligible. Planting a few trees in a bare ward buys almost nothing. Second, cool roofs
        are the reliable lever, about zero point six Kelvin per zero point one of albedo. Third,
        the one that changed my design: an exchange in Science between Bastin, who mapped global
        restoration potential, and Veldman, who pointed out much of that potential is native
        grassland where planting is actively harmful. Almost every greening tool answers heat
        with plant more trees. I could not do that honestly, so UCIP checks first, and says no
        when the answer is no.
    """)


def slide_08_priorart():
    slide = base_slide(8, 3, "What already ships, and the one check none of it runs",
                       sub="Capability marks below were checked against each live tool in August 2026, not taken from its press release.")

    rows = [
        ("WRI Cool Cities Lab  ·  web tool, 2026, 31 cities", "yes", "not surfaced",
         "yes", "no", "no"),
        ("Tree Equity Score  ·  web tool, US + UK", "yes", "yes", "trees only", "no",
         "partial"),
        ("C40 Urban Cooling Toolbox  ·  guidance", "no", "no", "yes", "no", "partial"),
        ("Azhar et al. 2017 India HVI  ·  research index", "district only", "partial",
         "no", "no", "no"),
        ("Mumbai CAP 2022, Ahmedabad HAP  ·  policy", "no", "no", "yes", "no", "no"),
        ("UCIP", "yes", "yes", "yes", "yes", "roadmap"),
    ]
    add_table(slide, MARGIN_L, 1.86, 11.94, 3.05,
              ["TOOL", "NEIGHBOURHOOD\nRANKING", "PER-FACTOR\nEXPLAINABILITY",
               "INTERVENTION\nENGINE", "ECOLOGICAL\nGUARDRAIL", "BUDGET\nLAYER"],
              rows, [4.44, 1.56, 1.86, 1.50, 1.50, 1.08],
              body_size=8.4, header_size=8.2, highlight_last=True)

    add_card_bg(slide, MARGIN_L, 5.10, 7.85, 1.35, fill=PANEL_NESTED, border=CRIMSON)
    add_body_text(
        slide,
        "The strongest tool here shipped five months ago, and still says plant trees.",
        MARGIN_L + 0.28, 5.29, 7.3, 0.38, size=14.5, color=WHITE, bold=True, font=FONT_HEAD,
    )
    add_body_text(
        slide,
        "WRI's Cool Cities Lab is good, open source, and genuinely models cooling. Nothing in it "
        "asks whether planting belongs in a cell first. That check is what I built.",
        MARGIN_L + 0.28, 5.72, 7.3, 0.55, size=10, color=MUTED, line_spacing=1.2,
    )

    add_stat_box(slide, 8.72, 5.10, 1.95, 1.35, "31",
                 "cities covered by the\nclosest comparable tool",
                 number_size=20, layout="stacked", number_color=AMBER)
    add_stat_box(slide, 10.83, 5.10, 1.95, 1.35, "0",
                 "of those 31 are Mumbai",
                 number_size=20, layout="stacked", number_color=EMERALD)

    set_notes(slide, """
        I want to be fair here, because the top row is genuinely good. WRI shipped Cool Cities
        Lab in March. It maps heat risk block by block, it is open source, it covers thirty one
        cities, and it models what trees and cool roofs would do. So if you are wondering
        whether someone already built this, roughly, yes. Two things it does not do. It does not
        cover Mumbai, and nothing in it checks whether planting belongs in a cell before
        recommending it. Tree Equity Score is the strongest on explainability, and it is US and
        UK only. Below those, the Indian work is a national index at district resolution, where
        all of Mumbai is about one pixel, and two policy documents. I checked every mark on this
        table against the live tool this month, and where I could not confirm something from the
        public interface I wrote not surfaced rather than guessing a no.
    """)


# ---------------------------------------------------------------------------
# 04 - PROPOSED SOLUTION
# ---------------------------------------------------------------------------

def slide_09_chain():
    slide = base_slide(9, 4, "The chain: rank, explain, recommend, check")

    steps = [
        ("01", "Rank", "One vulnerability score\nper ward, 0 to 100,\nweights derived from\nthe data itself"),
        ("02", "Explain", "Seven contribution bars\nper ward showing exactly\nwhich factor pushed\nthe score up"),
        ("03", "Recommend", "Five cited rules turn\nthe score into a specific\nintervention with a\npriority level"),
        ("04", "Check", "Ecological guardrail\nblocks tree planting\nwhere it would backfire,\nroutes to cool roofs"),
    ]
    bw = 2.72
    arrow_w = 0.38
    bx = MARGIN_L
    for i, (num, name, detail) in enumerate(steps):
        add_flow_box(slide, bx, 1.85, bw, 1.85, num, name, detail,
                     accent=[TEAL, TEAL, EMERALD, CRIMSON][i])
        bx += bw
        if i < 3:
            add_arrow(slide, bx + 0.06, 2.62, arrow_w - 0.12, 0.30)
            bx += arrow_w

    add_body_text(slide, "WHO ACTS ON IT", MARGIN_L, 4.10, 6.0, 0.26, size=9.5,
                  color=MUTED, font=FONT_MONO, bold=True)
    add_pill_list(slide, MARGIN_L, 4.42, 11.94, 1.88, [
        ("BMC planners:", "a priority list they can defend, where every ranking traces back to the "
                          "indicator that caused it."),
        ("Vulnerable residents:", "cooling investment lands where need is measurably highest, and "
                                  "the reasoning is public rather than internal."),
        ("Researchers and NGOs:", "open method, open data, open code, and a limitations section "
                                  "that is written down rather than discovered later."),
    ], gap=0.10, lead_size=11, rest_size=9.8)

    set_notes(slide, """
        The whole system in one line: rank, explain, recommend, check. Rank gives every ward a
        vulnerability score, weights derived from the data, not chosen by me. Explain breaks the
        score into seven contribution bars showing which factor pushed a ward up. Recommend runs
        five cited rules that turn the score into a specific intervention with a priority. Check
        is the ecological guardrail that blocks tree planting where it would backfire, routing
        those cells to cool roofs instead. Planners get an auditable priority list, residents get
        investment where need is measurably highest, and researchers get open method and data.
    """)


def slide_10_indicators():
    slide = base_slide(10, 4, "What goes into the score")

    rows = [
        ("Land-surface temperature", "+", "Direct exposure. The hazard itself.", "Landsat 8/9"),
        ("Green cover (NDVI)", "\u2212", "Vegetation cools. More green means less vulnerable.", "Landsat 8/9"),
        ("Population density", "+", "More people exposed per unit of area affected.", "WorldPop"),
        ("Elderly share", "+", "Heat mortality concentrates sharply with age.", "WorldPop"),
        ("Slum share", "+", "Heat-trapping roofs, low cooling access.", "Datameet"),
        ("Distance to hospital", "+", "Heat illness is time-critical. Access is protective.", "OSM"),
        ("Impervious / built-up", "+", "Concrete and asphalt store and re-radiate heat.", "ESA WorldCover"),
    ]
    add_table(slide, MARGIN_L, 1.80, 11.94, 3.35,
              ["INDICATOR", "DIR.", "WHY IT IS IN THE INDEX", "SOURCE"],
              rows, [3.20, 0.78, 5.86, 2.10], body_size=9.2)

    add_card_bg(slide, MARGIN_L, 5.35, 5.85, 1.10, fill=PANEL_NESTED)
    add_body_text(slide, "Direction is set by the literature, not by the maths.",
                  MARGIN_L + 0.26, 5.52, 5.35, 0.30, size=11, color=WHITE, bold=True)
    add_body_text(
        slide,
        "Green cover is the only inverted indicator. Reid 2009, Knowlton 2014 and Azhar 2017 all "
        "use this indicator family for heat vulnerability.",
        MARGIN_L + 0.26, 5.83, 5.35, 0.50, size=9.5, color=MUTED, line_spacing=1.18,
    )

    add_card_bg(slide, MARGIN_L + 6.09, 5.35, 5.85, 1.10, fill=PANEL_NESTED)
    add_body_text(slide, "Every indicator is standardised before it is combined.",
                  MARGIN_L + 6.35, 5.52, 5.35, 0.30, size=11, color=WHITE, bold=True)
    add_body_text(
        slide,
        "A z-score puts degrees Celsius, people per square kilometre and metres on the same scale, "
        "so no indicator wins simply because its units are bigger.",
        MARGIN_L + 6.35, 5.83, 5.35, 0.50, size=9.5, color=MUTED, line_spacing=1.18,
    )

    set_notes(slide, """
        Seven indicators go into the score, listed on screen with why each belongs and where it
        comes from. Two things worth saying: the direction of each indicator, whether higher means
        worse, is set by the published literature, not my maths. And every indicator is z-scored
        before combination, so degrees Celsius, people per square kilometre and metres end up on
        the same scale. No indicator wins just because its units are bigger.
    """)


def slide_11_weights():
    slide = base_slide(11, 4, "How the score is built")

    steps = [
        ("01", "Standardise", "z-score each\nof 7 indicators"),
        ("02", "Orient", "flip sign so higher\nalways means worse"),
        ("03", "Weight", "PCA, weights from\nPC1 loadings"),
        ("04", "Combine", "weighted sum,\nrescaled 0 to 100"),
    ]
    bw, gap = 1.56, 0.14
    bx = MARGIN_L
    for num, name, detail in steps:
        add_flow_box(slide, bx, 1.78, bw, 1.02, num, name, detail)
        bx += bw + gap

    add_callout(slide, MARGIN_L, 2.98, 6.90, 0.82, pct(F["pc1"]),
                "of total variance explained by the first principal component, comfortably above "
                "the 30 % floor, so PCA weights are used directly.",
                number_size=22, accent=EMERALD)

    add_body_text(slide, "WEIGHTS THIS RUN PRODUCED", MARGIN_L, 4.02, 6.0, 0.26, size=9.5,
                  color=MUTED, font=FONT_MONO, bold=True)

    labels = {
        "impervious_pct": "Impervious / built-up",
        "pop_density_km2": "Population density",
        "LST_C": "Land-surface temp",
        "NDVI": "Green cover (NDVI)",
        "hospital_dist_m": "Hospital distance",
        "slum_pct": "Slum index",
        "elderly_pct": "Elderly share",
    }
    ordered = sorted(F["weights"].items(), key=lambda kv: -kv[1])
    wmax = 0.20
    ry = 4.34
    for key, val in ordered:
        add_bar_row(slide, MARGIN_L, ry, 6.90, 0.30, labels[key], val / wmax, pct(val),
                    label_w=2.05, value_w=0.72)
        ry += 0.32

    add_card_bg(slide, 7.75, 1.78, 5.03, 2.02, fill=PANEL_NESTED, border=AMBER)
    add_dot_heading(slide, "The safety rule", 8.00, 1.96, 4.5, 0.28, size=12, dot=AMBER)
    add_body_text(
        slide,
        "If PC1 had explained less than 30 % of variance, the loadings would be unstable for a "
        "single-city, single-snapshot sample. The code detects that and falls back to equal "
        "weighting rather than trusting them.\n"
        "It did not trigger. But it is in the code, and the site prints which branch ran.",
        8.00, 2.34, 4.53, 1.36, size=9.8, color=MUTED, line_spacing=1.2, space_before=6,
    )

    add_crop_screenshot(slide, "deck-methodology-weights-dark.png", 7.75, 4.02, 5.03,
                        crop_l=0.21, crop_r=0.21, crop_t=0.10, crop_b=0.33,
                        max_h=2.28, center_in=5.03,
                        caption="The site reads these numbers straight from the pipeline's JSON output.")

    set_notes(slide, """
        The densest slide, so slowly. Four steps: standardise, orient so higher always means more
        vulnerable, derive weights, combine and rescale. The interesting step is weighting, where
        most indices quietly cheat by picking numbers that feel right. I follow Reid two thousand
        and nine and run a principal component analysis, taking the weights from the first
        component's loadings, so the data decides which indicators carry the index, not me. Here
        that component explains fifty eight percent of variance. Impervious surface weighs
        highest, elderly share lowest. And there is a safety rule: under thirty percent, the code
        falls back to equal weighting. It did not trigger, but the site prints which branch ran.
    """)


def slide_12_rules():
    slide = base_slide(12, 4, "From score to recommendation, with a guardrail")

    rows = [
        ("Native tree planting + green corridors",
         "Hot, low canopy, AND ecologically plantable", "Bastin 2019", "1"),
        ("Cool roofs + reflective pavements",
         "Hot, low canopy, but NOT plantable", "Veldman 2019", "1"),
        ("Cooling centres, priority siting",
         "High elderly share + poor hospital access", "Knowlton 2014", "1"),
        ("Rain gardens + water-sensitive design",
         "Highly impervious + near mapped water", "proxy, stated", "2"),
        ("Pocket parks",
         "High density + little existing open space", "C40 Toolbox", "3"),
    ]
    add_table(slide, MARGIN_L, 1.80, 7.85, 2.55,
              ["INTERVENTION", "FIRES WHEN", "CITATION", "PRI."],
              rows, [3.20, 2.90, 1.35, 0.40], body_size=8.8)

    add_card_bg(slide, MARGIN_L, 4.55, 7.85, 1.80, fill=PANEL_NESTED, border=CRIMSON)
    add_dot_heading(slide, "The guardrail, stated as code", MARGIN_L + 0.26, 4.74, 7.3, 0.28,
                    size=12, dot=CRIMSON)
    add_body_text(
        slide,
        "plantable  =  NOT built-up, water, wetland or mangrove\n"
        "                    AND  NOT native grassland\n"
        "                    AND  impervious cover below the 75th percentile",
        MARGIN_L + 0.26, 5.12, 7.3, 0.85, size=10, color=EMERALD, font=FONT_MONO,
        line_spacing=1.28, space_before=3,
    )
    add_body_text(
        slide,
        "Rules 1 and 2 are the same situation with opposite answers. The guardrail decides which.",
        MARGIN_L + 0.26, 6.00, 7.3, 0.30, size=9.5, color=MUTED,
    )

    stats = [
        (f"{F['n_nbs']}", "ward-level recommendations\ngenerated, across all 24 wards"),
        ("204", f"of {F['n_cells']} cells rejected for\nplanting by the guardrail"),
        ("5", "distinct interventions, each\ncarrying its own citation"),
    ]
    sy = 1.80
    for num, label in stats:
        add_stat_box(slide, 8.72, sy, 4.06, 1.05, num, label, number_size=20, layout="row")
        sy += 1.17

    add_card_bg(slide, 8.72, 5.35, 4.06, 1.00, fill=PANEL_NESTED)
    add_body_text(
        slide,
        "Thresholds are percentiles of this run, not fixed absolute cutoffs. Re-run on new imagery "
        "and they move with the city.",
        8.98, 5.52, 3.56, 0.70, size=9.5, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        A score on its own is still a diagnosis, so it feeds a rule engine: five rules, each
        emitting an intervention, a rationale, a citation and a priority. Look at the top two
        rows, the whole argument. Rules one and two fire on exactly the same situation, a hot ward
        with low canopy, and give opposite answers. If the cell is ecologically plantable, native
        tree planting, cited to Bastin. If not, cool roofs, cited to Veldman. The guardrail
        decides: not built up, water, wetland or mangrove; not native grassland; impervious cover
        below the seventy fifth percentile. It rejects two hundred and four of five hundred and
        forty one cells for planting. In total, eighty one recommendations across twenty four
        wards.
    """)


# ---------------------------------------------------------------------------
# 05 - PROTOTYPE / SOLUTION DESIGN
# ---------------------------------------------------------------------------

def slide_13_arch():
    slide = base_slide(13, 5, "Architecture")

    add_body_text(
        slide,
        "Google Earth Engine  \u2192  Python (geopandas, scikit-learn, osmnx, scipy)  \u2192  "
        "Supabase + PostGIS  \u2192  Next.js 16 + Leaflet + three.js  \u2192  Vercel",
        MARGIN_L, 1.36, 11.94, 0.32, size=10.5, color=TEAL, font=FONT_MONO,
    )

    boxes = [
        ("01", "Open data", "Landsat 8/9\nWorldCover\nWorldPop\nOSM, Datameet"),
        ("02", "Python pipeline", f"{F['n_stages']} numbered stages\ngrid, zonal stats,\nPCA index,\nrule engine"),
        ("03", "Storage", "Supabase Postgres\n+ PostGIS\nand static GeoJSON\nsnapshots"),
        ("04", "Web app", "Next.js 16, React 19\nLeaflet choropleth\nthree.js hero\n8 static routes"),
        ("05", "Deploy", "Vercel\nstatic prerender\nno server-side\ndata calls"),
    ]
    bw = 2.16
    arrow_w = 0.32
    bx = MARGIN_L
    for i, (num, name, detail) in enumerate(boxes):
        add_flow_box(slide, bx, 1.85, bw, 1.62, num, name, detail)
        bx += bw
        if i < 4:
            add_arrow(slide, bx + 0.04, 2.52, arrow_w - 0.08, 0.28)
            bx += arrow_w

    stats = [
        (f"{F['n_wards']}", "wards scored"),
        (f"{F['n_cells']}", "1 km grid cells"),
        (f"{F['n_nbs']}", "cited recommendations"),
        (f"{F['n_stages']}", "pipeline stages"),
        (f"{F['n_citations']}", "papers, DOIs verified"),
    ]
    bw2, gap2 = 2.30, 0.16
    bx = MARGIN_L
    for num, label in stats:
        add_stat_box(slide, bx, 3.68, bw2, 0.92, num, label, number_size=20)
        bx += bw2 + gap2

    add_card_bg(slide, MARGIN_L, 4.80, 11.94, 1.62, fill=PANEL_NESTED, border=EMERALD)
    add_dot_heading(slide, "The design decision I would defend hardest", MARGIN_L + 0.30, 4.98,
                    8.0, 0.28, size=12.5, dot=EMERALD)
    add_body_text(
        slide,
        "The loader writes GeoJSON snapshots first and unconditionally, then attempts the database "
        "load on a best-effort basis. The shipped frontend never imports the Supabase client at "
        "all. On 21 July I verified this by blocking supabase.co and earthengine.googleapis.com at "
        "the network layer and walking the entire judged flow. Zero errors. The demo cannot die "
        "from a dead network dependency, and that was a deliberate choice made on day zero rather "
        "than a patch applied after something broke.",
        MARGIN_L + 0.30, 5.36, 11.34, 0.95, size=10.2, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        Architecture, five stages left to right. Open data from Earth Engine, a Python pipeline
        of thirteen stages, results to Supabase and static GeoJSON, a Next.js app on Vercel.
        Scale is twenty four wards, five hundred and forty one cells, eighty one recommendations
        and eleven cited papers. The design decision I would defend hardest: the loader
        writes static snapshots first and unconditionally, only then tries the database, and the
        shipped frontend never imports the Supabase client at all. I tested that by blocking
        Supabase and Earth Engine at the network layer and walking the whole flow. Zero errors.
        This demo cannot die from a dead dependency, and that was decided on day zero.
    """)


def slide_14_dashboard():
    slide = base_slide(14, 5, "The dashboard")

    # Full frame, no right crop: cutting mid-sidebar left truncated labels on screen.
    add_crop_screenshot(slide, "deck-dashboard-hvi-dark.png", MARGIN_L, 1.80, 8.05,
                        crop_l=0.0, crop_r=0.0, crop_t=0.055, crop_b=0.0,
                        max_h=4.42, center_in=8.05,
                        caption="Twenty four wards, coloured by vulnerability, ranked in the sidebar, "
                                "with a persistent legend.")

    add_body_text(slide, "MOST VULNERABLE, COMPUTED NOT CHOSEN", 8.92, 1.80, 4.0, 0.26,
                  size=9.5, color=MUTED, font=FONT_MONO, bold=True)

    ranked_names = {"C": "Marine Lines, Kalbadevi", "G/N": "Dadar, Mahim, Dharavi",
                    "L": "Kurla", "E": "Byculla, Mazgaon", "F/S": "Parel, Lalbaug, Sewri"}
    ry = 2.14
    for i, (wid, hvi) in enumerate(F["top5"], start=1):
        add_card_bg(slide, 8.92, ry, 3.86, 0.52, fill=PANEL_NESTED)
        add_body_text(slide, str(i), 9.08, ry, 0.30, 0.52, size=11, color=MUTED,
                      font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE)
        add_body_text(slide, f"Ward {wid}", 9.42, ry, 1.30, 0.52, size=11.5, color=WHITE,
                      bold=True, anchor=MSO_ANCHOR.MIDDLE)
        add_body_text(slide, ranked_names[wid], 10.62, ry, 1.55, 0.52, size=8.2, color=MUTED,
                      anchor=MSO_ANCHOR.MIDDLE)
        add_body_text(slide, f"{hvi:.1f}", 11.98, ry, 0.66, 0.52, size=11.5, color=CRIMSON,
                      bold=True, font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE, align=PP_ALIGN.RIGHT)
        ry += 0.60

    add_card_bg(slide, 8.92, 5.20, 3.86, 1.02, fill=PANEL_NESTED)
    add_body_text(
        slide,
        "Search resolves locality names, so typing \"Dharavi\" finds Ward G/N. Every ward is a "
        "shareable link, and browser Back steps through your selections.",
        9.18, 5.38, 3.36, 0.72, size=9.3, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        This is the product: twenty four wards coloured by vulnerability, ranked in the sidebar.
        The five most vulnerable, C, G slash N, L, E and F slash S, are computed, not chosen. I
        did not pick Dharavi because it is the famous answer, G slash N contains Dharavi and came
        second on its own. Two usability details: the search box resolves locality names, so
        typing Dharavi finds ward G slash N, and every ward is a shareable URL, so a planner can
        send a colleague one specific ward rather than a screenshot.
    """)


def slide_15_explain():
    slide = base_slide(15, 5, "Ward C: explainability, end to end")

    # Sidebar-only crop, so this is portrait. Width is derived from max_h, not the other way round.
    add_crop_screenshot(slide, "deck-ward-c-dark.png", MARGIN_L, 1.80, 7.30,
                        crop_l=0.752, crop_r=0.005, crop_t=0.055, crop_b=0.0,
                        max_h=4.42, center_in=7.30,
                        caption="Every number on this panel is a lookup, not a second model.")

    add_card(slide, 8.20, 1.80, 4.58, 1.62, "Generated, not hand-written",
             "\"Ward C runs about 3.4 \u00b0C hotter than the city average across its 2 grid cells, "
             "at 35.8 \u00b0C of land surface temperature.\" Deterministic prose over the profile "
             "data. No language model in the loop.", body_size=9.5)

    add_card(slide, 8.20, 3.58, 4.58, 1.42, "Seven contribution bars",
             "Each bar is literally weight multiplied by z-score. Red pushed this ward up, green "
             "pulled it down. It is the same arithmetic that produced the score, shown back to you.",
             body_size=9.5, dot=CRIMSON)

    add_card_bg(slide, 8.20, 5.16, 4.58, 1.06, fill=PANEL_NESTED, border=EMERALD)
    add_body_text(slide, "No black box, and no SHAP either.", 8.46, 5.33, 4.06, 0.30,
                  size=11.5, color=WHITE, bold=True)
    add_body_text(
        slide,
        "A linear index does not need a post-hoc explainer. Refusing to add one was a design "
        "choice, recorded in the code.",
        8.46, 5.64, 4.06, 0.50, size=9.3, color=MUTED, line_spacing=1.2,
    )

    set_notes(slide, """
        Click the worst ward: Ward C, Mumbai's old fort and market core. At the top, three
        sentences generated deterministically from the ward profile data, no language model in
        that loop, every number is a field lookup, so it cannot hallucinate. Below that, city
        averages on all seven indicators, then the seven contribution bars: each is literally the
        weight multiplied by the z-score, red pushed the score up, green pulled it down. That is
        not an approximation of the model, it is the model, which is why there is no SHAP here. At
        the bottom, the recommended intervention, with its paper as a clickable DOI.
    """)


def slide_16_guardrail():
    slide = base_slide(16, 5, "The guardrail, running on real data")

    _, _, _, ph = add_crop_screenshot(
        slide, "deck-ward-a-plantability-dark.png", MARGIN_L, 1.80, 7.30,
        crop_l=0.0, crop_r=0.245, crop_t=0.055, crop_b=0.0,
        max_h=4.05, center_in=7.30)
    add_body_text(
        slide,
        "Ward A. Green cells are ecologically suitable for planting, red cells are routed to cool "
        "roofs instead. The same ward carries both answers.",
        MARGIN_L, 1.80 + ph + 0.10, 7.30, 0.42, size=9, color=MUTED, align=PP_ALIGN.CENTER,
        line_spacing=1.15,
    )

    add_card_bg(slide, 8.20, 1.80, 4.58, 2.28, border=CRIMSON)
    add_dot_heading(slide, "Two recommendations, one ward", 8.46, 1.98, 4.06, 0.28,
                    size=12, dot=CRIMSON)
    add_body_text(
        slide,
        "\u25B8  Cool roofs + reflective pavements\n"
        "     \"afforestation would backfire ecologically\"\n"
        "     Veldman et al. 2019\n\n"
        "\u25B8  Native tree planting + green corridors\n"
        "     \"ecologically suitable for restoration\"\n"
        "     Bastin et al. 2019",
        8.46, 2.36, 4.10, 1.58, size=9.5, color=MUTED, line_spacing=1.22, space_before=2,
    )

    add_card_bg(slide, 8.20, 4.24, 4.58, 1.10, fill=PANEL_NESTED)
    add_body_text(slide, "Most tools cannot produce this pair.", 8.46, 4.42, 4.06, 0.28,
                  size=11, color=WHITE, bold=True)
    add_body_text(
        slide,
        "A tool that answers heat with \"plant trees\" has no way to say no. Saying no is the "
        "feature.",
        8.46, 4.72, 4.06, 0.50, size=9.3, color=MUTED, line_spacing=1.2,
    )

    add_crop_screenshot(slide, "deck-simulate-dark.png", 8.20, 5.44, 4.58,
                        crop_l=0.21, crop_r=0.21, crop_t=0.745, crop_b=0.02,
                        max_h=0.90, center_in=4.58,
                        caption="The what-if estimator, also cited coefficient by coefficient.",
                        caption_size=8.5)

    set_notes(slide, """
        The slide I would point at for what makes UCIP different. The plantability layer is a
        green and red mosaic: green cells are ecologically suitable for planting, red cells route
        to cool roofs. This is Ward A, and it carries both answers at once. Cool roofs, because
        afforestation would backfire, cited to Veldman. Directly below, native tree planting,
        suitable for restoration, cited to Bastin. Same ward, opposite advice, different cells,
        both traceable to a paper. A tool that answers heat with plant trees cannot produce that
        pair, because it has no way to say no. Saying no is the feature. Underneath, the what-if
        estimator lets you move sliders and watch a cited estimate recompute.
    """)


def slide_17_holdup():
    slide = base_slide(17, 5, "Does it hold up?",
                       sub="The hardest question a researcher can ask an index is whether the answer survives the weights changing.")

    _, _, _, sh = add_crop_screenshot(
        slide, "deck-methodology-sensitivity-dark.png", MARGIN_L, 1.92, 7.30,
        crop_l=0.235, crop_r=0.235, crop_t=0.28, crop_b=0.28,
        max_h=3.36, center_in=7.30)
    add_body_text(
        slide,
        f"All {F['n_runs']} perturbation runs, plotted. Every bar sits near 1.0.",
        MARGIN_L, 1.92 + sh + 0.10, 7.30, 0.30, size=9, color=MUTED, align=PP_ALIGN.CENTER,
    )

    add_body_text(slide, "THE TEST", MARGIN_L, 5.76, 3.0, 0.26, size=9.5, color=MUTED,
                  font=FONT_MONO, bold=True)
    add_body_text(
        slide,
        f"Perturb each of the 7 weights by \u00b1{F['perturb'] * 100:.0f} %, one at a time, "
        f"renormalise, and recompute the entire ward ranking. {F['n_runs']} runs.",
        MARGIN_L, 6.06, 7.30, 0.55, size=10, color=MUTED, line_spacing=1.2,
    )

    add_stat_box(slide, 8.20, 1.92, 4.58, 1.22, f"{F['tau']:.3f}",
                 "mean Kendall tau against the baseline ranking. 1.0 would be a perfectly "
                 "identical order.", number_size=26, layout="row")
    add_stat_box(slide, 8.20, 3.28, 4.58, 1.22, f"{F['overlap']:.1f} / 5",
                 "mean overlap in the top five wards across every perturbation run.",
                 number_size=26, layout="row", number_color=AMBER)

    add_card_bg(slide, 8.20, 4.64, 4.58, 1.97, fill=PANEL_NESTED, border=AMBER)
    add_dot_heading(slide, "Where it is not perfect", 8.46, 4.82, 4.06, 0.28, size=12, dot=AMBER)
    add_body_text(
        slide,
        "The overlap is 4.4, not 5. In 2 of the 14 runs the fifth ward swaps.\n"
        "The reason is not instability in the method. Ward F/S scores 64.838 and Ward B scores "
        "64.819. They are 0.019 apart, which is a tie in any practical sense.\n"
        "I would rather show you that than round it away.",
        8.46, 5.20, 4.10, 1.32, size=9.4, color=MUTED, line_spacing=1.2, space_before=5,
    )

    set_notes(slide, """
        The hardest question you can ask an index is whether the answer survives the weights
        changing, so I tested it before you could ask. I perturbed each weight by plus and minus
        twenty percent, one at a time, and recomputed the whole ranking across fourteen runs.
        Mean Kendall tau against the baseline is zero point nine seven eight, where one would be
        identical. Mean overlap in the top five is four point four out of five. In two runs the
        fifth ward swaps, but that is not instability: Ward F slash S and Ward B are nineteen
        thousandths of a point apart, and any perturbation flips a tie.
    """)


# ---------------------------------------------------------------------------
# 06 - IMPACT & FUTURE SCOPE
# ---------------------------------------------------------------------------

def slide_18_limits():
    slide = base_slide(18, 6, "Limitations, stated openly")

    items = [
        ("Land-surface temperature is not air temperature.",
         "Satellites measure the temperature of the ground, not what a person standing on it feels. "
         "The two correlate but they are not the same number, and the site says so on the landing page."),
        ("Cooling coefficients are transferred, not Mumbai-calibrated.",
         "Ziter measured Madison, Bowler is a global meta-analysis. I apply their numbers to Mumbai "
         "because no local field study exists yet. That is an assumption, not a measurement."),
        ("Slum and elderly layers are proxies.",
         "WorldPop 2020 modelled rasters and mapped slum-cluster boundaries, not a ward-level "
         "census. Elderly share varies only from 4.0 to 5.6 % across the whole city, so it "
         "separates wards weakly, and I do not lean on it."),
        ("The what-if estimator is first-order, not a climate model.",
         "It sums three cited coefficients as independent terms. There is no coupled physics and "
         "no check for double-counting between canopy and park area."),
        ("The plantability layer is coarse.",
         "10 m land-cover classes aggregated to a 1 km cell. It is good enough to catch grassland, "
         "not good enough to site an individual tree."),
    ]
    y = 1.72
    for lead, rest in items:
        add_card_bg(slide, MARGIN_L, y, 8.30, 0.86, fill=PANEL_NESTED)
        add_lead_body(slide, MARGIN_L + 0.24, y + 0.10, 7.85, 0.70, "\u25B8  " + lead, rest,
                      lead_size=10.5, rest_size=9.3, line_spacing=1.18)
        y += 0.94

    add_card_bg(slide, 9.20, 1.72, 3.58, 4.66, border=EMERALD)
    add_dot_heading(slide, "Why this slide exists", 9.46, 1.94, 3.1, 0.28, size=12.5)
    add_body_text(
        slide,
        "Most city heat tools present their outputs as more certain than they are. A planner then "
        "acts on that certainty, and when it turns out to be wrong the whole category loses "
        "credibility.\n\n"
        "This is the product feature I am most confident about.\n\n"
        "Every one of these limits is on the public methodology page, not just in this deck. The "
        "small-ward caveat is there too. Ward C ranks first on only 2 grid cells, while Ward R/C "
        "has 61, so small wards are noisier by construction.\n\n"
        "If you find a limitation I have not listed, I want to hear it, and it goes on the page.",
        9.46, 2.34, 3.10, 3.90, size=9.6, color=MUTED, line_spacing=1.22, space_before=6,
    )

    set_notes(slide, """
        The part most pitches skip: five limitations, listed on screen. Land surface temperature
        is not air temperature. Cooling coefficients are transferred, not Mumbai calibrated: Ziter
        measured Madison, Wisconsin, and I apply that here because no local study exists yet, an
        assumption, not a
        measurement. My slum and elderly layers are proxies, not census. The what-if estimator
        sums three coefficients with no coupled physics, and the plantability layer is coarse,
        good enough to catch grassland, not to site an individual tree. Why put this on a slide:
        most heat tools present outputs as more certain than they are, and when that breaks, the
        whole category loses credibility. Every one of these is on the public methodology page.
    """)


def slide_19_impact():
    slide = base_slide(19, 6, "Impact")

    add_card(slide, MARGIN_L, 1.78, 3.86, 2.42, "For Mumbai",
             "Mumbai already knows it is hot. This says where to start. A planner with a finite "
             "budget gets a starting order they can defend in a room, instead of an instinct they "
             "cannot show anyone.", dot=TEAL)

    add_card(slide, MARGIN_L + 4.04, 1.78, 3.86, 2.42, "For other cities",
             "Every input is free and public. Moving to Pune, Ahmedabad or Delhi costs a boundary "
             "file, not a new method and not a data budget. The pipeline and the citations travel "
             "as they are.", dot=EMERALD)

    add_card(slide, MARGIN_L + 8.08, 1.78, 3.86, 2.42, "For the field",
             "Apache 2.0, public repository, method and limitations documented in the open. The "
             "guardrail idea in particular is worth copying, whatever happens to this specific "
             "tool.", dot=AMBER)

    add_body_text(slide, "WHAT CHANGES ON MONDAY MORNING", MARGIN_L, 4.48, 6.0, 0.26,
                  size=9.5, color=MUTED, font=FONT_MONO, bold=True)
    add_pill_list(slide, MARGIN_L, 4.80, 11.94, 1.55, [
        ("A planner", "opens one URL, sorts 24 wards by measured need, and can show the reasoning "
                      "to a committee, factor by factor, with a paper behind each one."),
        ("A resident", "types their neighbourhood name, sees their own ward's score and what is "
                       "recommended for it, and can read exactly what the tool does not know."),
    ], gap=0.12, lead_size=11, rest_size=9.8)

    set_notes(slide, """
        Impact, three audiences. Mumbai already knows it is hot. This says where to start, and a
        planner with a finite budget gets an order they can defend in a room instead of an
        instinct they cannot show anyone. For other cities, the part I think matters most, every
        input is free and public, so moving costs a boundary file rather than a new method. For
        the field, it is Apache two point zero and public, so the guardrail idea is worth copying
        whatever happens to this tool. On a Monday morning: a planner opens one URL, sorts wards
        by measured need, and can walk a committee through it factor by factor. A resident finds
        their ward and reads exactly what the tool does not know.
    """)


def slide_20_future():
    slide = base_slide(20, 6, "Future scope")

    items = [
        ("Finer grid, 1 km to 500 m.",
         "A single constant in the grid stage. It quadruples cell count and directly fixes the "
         "small-ward noise problem, because Ward C would stop resting on 2 cells."),
        ("Mumbai-calibrated cooling coefficients.",
         "Replace the transferred Madison and meta-analysis numbers with local field measurement. "
         "This is the limitation I would most like to close."),
        ("Budget allocation layer.",
         "Maximise vulnerability reduction per rupee across wards. This is the fifth capability "
         "from the matrix on slide eight. Designed, not built, and not claimed."),
        ("Census-linked demographics.",
         "Replace the WorldPop and slum-cluster proxies with real ward-level counts when they "
         "become accessible."),
        ("Replication kit.",
         "Config-driven port to another city, so the boundary file is the only thing that changes."),
    ]
    y = 1.72
    for lead, rest in items:
        add_card_bg(slide, MARGIN_L, y, 7.85, 0.84, fill=PANEL_NESTED)
        add_lead_body(slide, MARGIN_L + 0.24, y + 0.10, 7.40, 0.68, "\u25B8  " + lead, rest,
                      lead_size=10.5, rest_size=9.3, line_spacing=1.18)
        y += 0.92

    add_card_bg(slide, 8.72, 1.72, 4.06, 2.10, border=TEAL)
    add_dot_heading(slide, "Honest status", 8.98, 1.92, 3.5, 0.28, size=12, dot=TEAL)
    add_body_text(
        slide,
        "Rows one, two and four are extensions of something that already works.\n"
        "Row three is the one thing this deck promised nowhere else: the budget layer does not "
        "exist yet, and I have kept it off every earlier slide.",
        8.98, 2.32, 3.56, 1.36, size=9.5, color=MUTED, line_spacing=1.22, space_before=6,
    )

    add_gradient_bar(slide, x=8.72, y=4.10, w=1.3, h=0.06)
    add_body_text(slide, "UCIP.\nWhere to start,\nand what to build there.",
                  8.72, 4.36, 4.06, 1.30, size=20, color=WHITE, bold=True,
                  font=FONT_HEAD, line_spacing=1.18)

    add_card_bg(slide, 8.72, 5.82, 4.06, 0.56, fill=PANEL_NESTED)
    add_body_text(slide, "github.com/AnayDhawan/UCIP", 8.98, 5.82, 3.56, 0.56, size=10.5,
                  color=TEAL, font=FONT_MONO, anchor=MSO_ANCHOR.MIDDLE)

    add_body_text(
        slide,
        "Apache 2.0. Every data source free and public. Thank you, and I am happy to take "
        "questions on the method.",
        MARGIN_L, 6.40, 7.85, 0.40, size=10, color=MUTED,
    )

    set_notes(slide, """
        Five things, where this goes next, listed on screen: a finer grid down to five hundred
        metres, fixing the small-ward noise problem since Ward C would stop resting on two cells;
        Mumbai calibrated cooling coefficients, the limitation I would most like to close; the
        budget allocation layer, which does not exist yet; census linked demographics when
        accessible; and a replication kit so another city only changes a boundary file. To close:
        UCIP tells you where to start and what to build there. Apache two point zero, every data
        source free and public, repo on screen. Thank you, I am happy to take questions.
    """)


# ---------------------------------------------------------------------------
# Backup + validation + main
# ---------------------------------------------------------------------------

BUILDERS = [
    slide_01_title, slide_02_claim,
    slide_03_uneven, slide_04_who, slide_05_matters,
    slide_06_measured, slide_07_literature, slide_08_priorart,
    slide_09_chain, slide_10_indicators, slide_11_weights, slide_12_rules,
    slide_13_arch, slide_14_dashboard, slide_15_explain, slide_16_guardrail, slide_17_holdup,
    slide_18_limits, slide_19_impact, slide_20_future,
]

SLIDE_SECTION = [1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6]


def backup_existing():
    if os.path.exists(OUT_PATH) and not os.path.exists(BACKUP_PATH):
        shutil.copy2(OUT_PATH, BACKUP_PATH)
        print(f"Backed up previous 6-slide deck -> {os.path.basename(BACKUP_PATH)}")


def validate(path):
    p2 = Presentation(path)
    n = len(p2.slides)
    assert n == TOTAL_SLIDES, f"expected {TOTAL_SLIDES} slides, got {n}"

    print(f"\n{'#':<4} {'SEC':<5} {'TITLE':<44} {'SHAPES':>7} {'PICS':>5} {'WORDS':>6} {'TIME':>7}")
    print("-" * 84)

    total_words = 0
    total_shapes = 0
    problems = []

    for i, slide in enumerate(p2.slides, start=1):
        shapes = list(slide.shapes)
        n_shapes = len(shapes)
        n_pics = sum(1 for s in shapes if s.shape_type == MSO_SHAPE_TYPE.PICTURE)
        total_shapes += n_shapes

        if n_shapes == 1:
            problems.append(f"Slide {i} has only 1 shape, flattened-image regression detected")

        notes = ""
        if slide.has_notes_slide:
            notes = slide.notes_slide.notes_text_frame.text.strip()
        if not notes:
            problems.append(f"Slide {i} has no speaker notes")
        words = len(notes.split())
        total_words += words
        secs = words / WPM * 60

        title = ""
        for s in shapes:
            if s.has_text_frame and s.text_frame.text:
                txt = " ".join(s.text_frame.text.split())
                if len(txt) > 12 and not txt.isupper():
                    title = txt[:42]
                    break

        # em dash check across slide text and notes
        for s in shapes:
            if s.has_text_frame and "\u2014" in s.text_frame.text:
                problems.append(f"Slide {i} contains an em dash in slide text")
        if "\u2014" in notes:
            problems.append(f"Slide {i} contains an em dash in speaker notes")

        print(f"{i:<4} {SLIDE_SECTION[i-1]:<5} {title:<44} {n_shapes:>7} {n_pics:>5} "
              f"{words:>6} {int(secs//60)}:{int(secs%60):02d}")

    total_sec = total_words / WPM * 60
    print("-" * 84)
    print(f"{'':<4} {'':<5} {'TOTAL':<44} {total_shapes:>7} {'':>5} {total_words:>6} "
          f"{int(total_sec//60)}:{int(total_sec%60):02d}")

    if not (MIN_TOTAL_SEC <= total_sec <= MAX_TOTAL_SEC):
        problems.append(
            f"Spoken time {total_sec/60:.1f} min is outside the {MIN_TOTAL_SEC/60:.1f} to "
            f"{MAX_TOTAL_SEC/60:.1f} min window ({total_words} words at {WPM:.0f} wpm)"
        )

    print()
    if problems:
        for p in problems:
            print(f"  FAIL  {p}")
        raise RuntimeError(f"{len(problems)} validation problem(s)")

    print(f"  ok  {TOTAL_SLIDES} slides, all sections present")
    print(f"  ok  every slide has speaker notes")
    print(f"  ok  spoken time {total_sec/60:.1f} min, inside the {MIN_TOTAL_SEC/60:.0f} to "
          f"{MAX_TOTAL_SEC/60:.0f} min window")
    print(f"  ok  no em dashes")
    print(f"  ok  no flattened-image regression")
    print(f"\nFile size: {os.path.getsize(path) / (1024*1024):.2f} MB")
    print(f"Saved to:  {path}")


REQUIRED_SHOTS = [
    "deck-hero-dark.png",
    "deck-dashboard-hvi-dark.png",
    "deck-ward-c-dark.png",
    "deck-ward-a-plantability-dark.png",
    "deck-simulate-dark.png",
    "deck-methodology-weights-dark.png",
    "deck-methodology-sensitivity-dark.png",
    "deck-global-lst-may2026.png",
]


def check_shots():
    missing = [f for f in REQUIRED_SHOTS if not os.path.exists(os.path.join(SHOTS, f))]
    if missing:
        raise FileNotFoundError(
            "Missing screenshot(s) in deck-assets: " + ", ".join(missing)
            + "\nRe-capture them against a running dev server before building."
        )


def main():
    check_shots()
    backup_existing()
    for build in BUILDERS:
        build()
    prs.save(OUT_PATH)
    validate(OUT_PATH)


if __name__ == "__main__":
    main()
