/**
 * City configuration for the frontend.
 *
 * Reads a build-time mirror of config/cities/<slug>.json, the same file
 * pipeline/_city.py loads (issue #68). One config, two languages, so the map
 * centre the browser flies to and the bbox the pipeline validates its grid
 * against cannot drift apart. Before this, the centre was a hardcoded
 * MUMBAI_CENTER in WardChoropleth.tsx and the timezone a separate literal here,
 * neither aware of the other.
 *
 * The mirror under ./cities/ exists because Turbopack will not import a module
 * from outside the Next.js root, and reading it at runtime would stall the map
 * on a fetch for data that never changes between deploys. It is generated by
 * pipeline/sync_city_config.py and CI fails if it has drifted, so the copy
 * cannot quietly diverge from the config the pipeline actually used.
 *
 * Only Mumbai is wired up here, because Mumbai is the only city this deployment
 * publishes. Pune has a config and a working grid but no completed pipeline run,
 * so pointing the site at it would show an empty map. Adding a city to the site
 * means importing its mirror and switching ACTIVE_CITY, deliberately, once its
 * data exists.
 */

import mumbai from "./cities/mumbai.json";

export type CityConfig = {
  slug: string;
  name: string;
  /** Map centre as [lat, lon], the order Leaflet takes. */
  center: [number, number];
  zoom: number;
  /** [min_lon, min_lat, max_lon, max_lat], WGS84. */
  bbox: [number, number, number, number];
  lat: number;
  lon: number;
  timezone: string;
};

type RawCityConfig = {
  slug: string;
  name: string;
  timezone: string;
  bbox: number[];
  map: { center: number[]; zoom?: number };
};

function toCityConfig(raw: RawCityConfig): CityConfig {
  const [lat, lon] = raw.map.center;
  return {
    slug: raw.slug,
    name: raw.name,
    center: [lat, lon],
    zoom: raw.map.zoom ?? 11,
    bbox: raw.bbox as [number, number, number, number],
    // `lat`/`lon` are kept as flat fields because the live-weather widget takes
    // a point rather than a map view, and it read them off this shape before
    // the config existed.
    lat,
    lon,
    timezone: raw.timezone,
  };
}

export const MUMBAI: CityConfig = toCityConfig(mumbai as RawCityConfig);

/** The city this deployment is showing. */
export const ACTIVE_CITY: CityConfig = MUMBAI;
